### ISSUE TITLE
Documentation for parameters in findHomography 

### ISSUE THREAD

**Issue by anorak94** [ducha-aiki/pydegensac#10]
Hey thanks for the wonderful library. I also saw your tutorial for CVPR2020 it was very illuminating. Sorry if my question seems a bit naive. But what is the px_th in pydegensac.findHomography. Is it the error between held out pixels when computing the confidence score after estimating the homography. 

Thanks 
Anurag

**Comment by ducha-aiki** [comment]
`px_th` is a threshold on reprojection error, below which correspondence is considered inlier and above - outlier.
It is corresponding to the `t` from this Wiki RANSAC pseudocode

https://en.wikipedia.org/wiki/Random_sample_consensus
![image](https://user-images.githubusercontent.com/4803565/118618384-d978a400-b7c3-11eb-90a0-fc4dbd758843.png)

**Comment by anorak94** [comment]
Ah ok thanks a lot
