### ISSUE TITLE
Using TPS instead of homography

### ISSUE THREAD

**Issue by anorak94** [ducha-aiki/pydegensac#11]
Is it possible to use thin plate splines instead of the homography matrix estimation in pydegensac. Or for instance any black box deformable shape models.

**Comment by ducha-aiki** [comment]
Hi,
Not now at least. pydegensac is a version of RANSAC algorithm and I am not aware about existence of any thin plate RANSAC.
You can code thin-plate estimator yourself, it would require to implement, at least, minimum solver and non-minimum solver estimators.  The easiest way to start with that is skimage RANSAC, which is highly modular - you just need to provide solvers I mentioned.

https://scikit-image.org/docs/0.14.x/auto_examples/transform/plot_matching.html
