### ISSUE TITLE
About the degeneracy check

### ISSUE THREAD

**Issue by AoxiangFan** [ducha-aiki/pydegensac#13]
Thank you for the great work!

I am trying to understand the degeneracy check (and updating F) part of the code, but the C code seems to be really hard to decipher. So I want to ask do you have the MATLAB code for the degeneracy part (which appears in the C source code)? Or other instructions on implementing the degeneracy part could also help.

Thanks for your time and looking forward to your reply.

**Comment by ducha-aiki** [comment]
You can check probably more human-friendly implementation in OpenCV by @ivashmak 
https://github.com/opencv/opencv/blob/master/modules/calib3d/src/usac/degeneracy.cpp#L165
