### ISSUE TITLE
build fail 

### ISSUE THREAD

**Issue by xunfeng2zkj** [ducha-aiki/pydegensac#14]
sudo python3 ./setup.py build
/first_disk/TopKWindows/pydegensac/./setup.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
/usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'extra_compile_args'
  warnings.warn(msg)
running build
running build_py
running build_ext
-- pybind11 v2.1.1
-- Configuring done
-- Generating done
-- Build files have been written to: /first_disk/TopKWindows/pydegensac/build/temp.linux-x86_64-3.10
Consolidate compiler generated dependencies of target pydegensac_support
[ 17%] Built target pydegensac_support
Consolidate compiler generated dependencies of target matutls
[ 97%] Built target matutls
Consolidate compiler generated dependencies of target pydegensac
[ 98%] Linking CXX shared module ../lib.linux-x86_64-3.10/pydegensac/pydegensac.cpython-310-x86_64-linux-gnu.so
/usr/bin/ld: libpydegensac_support.a(exp_ranH.c.o):(.bss+0x0): multiple definition of `HASH_TABLE'; libpydegensac_support.a(exp_ranF.c.o):(.bss+0x0): first defined here
/usr/bin/ld: libpydegensac_support.a(hash.c.o):(.bss+0x0): multiple definition of `HASH_TABLE'; libpydegensac_support.a(exp_ranF.c.o):(.bss+0x0): first defined here
/usr/bin/ld: libpydegensac_support.a(DegUtils.c.o):(.bss+0x0): multiple definition of `pfc'; libpydegensac_support.a(Ftools.c.o):(.bss+0x0): first defined here
/usr/bin/ld: libpydegensac_support.a(DegUtils.c.o):(.bss+0x8): multiple definition of `pma'; libpydegensac_support.a(Ftools.c.o):(.bss+0x8): first defined here
/usr/bin/ld: libpydegensac_support.a(DegUtils.c.o):(.bss+0x10): multiple definition of `par'; libpydegensac_support.a(Ftools.c.o):(.bss+0x10): first defined here
/usr/bin/ld: libpydegensac_support.a(DegUtils.c.o):(.bss+0x18): multiple definition of `ndif'; libpydegensac_support.a(Ftools.c.o):(.bss+0x18): first defined here
/usr/bin/ld: libpydegensac_support.a(DegUtils.c.o):(.bss+0x1c): multiple definition of `nfc'; libpydegensac_support.a(Ftools.c.o):(.bss+0x1c): first defined here
/usr/bin/ld: libpydegensac_support.a(DegUtils.c.o):(.bss+0x20): multiple definition of `nar'; libpydegensac_support.a(Ftools.c.o):(.bss+0x20): first defined here
/usr/bin/ld: libpydegensac_support.a(DegUtils.c.o):(.bss+0x24): multiple definition of `nma'; libpydegensac_support.a(Ftools.c.o):(.bss+0x24): first defined here
/usr/bin/ld: libpydegensac_support.a(DegUtils.c.o):(.bss+0x28): multiple definition of `np'; libpydegensac_support.a(Ftools.c.o):(.bss+0x28): first defined here
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp: In function ‘findHomography_’:
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:206:25: warning: ‘SymCheck_th’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  206 |     exp_ransacHcustomLAF(u2,
      |                         ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:64:29: note: ‘SymCheck_th’ was declared here
   64 |     double error_threshold, SymCheck_th;
      |                             ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:206:25: warning: ‘error_threshold’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  206 |     exp_ransacHcustomLAF(u2,
      |                         ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:64:12: note: ‘error_threshold’ was declared here
   64 |     double error_threshold, SymCheck_th;
      |            ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:206:25: warning: ‘HDSidx1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  206 |     exp_ransacHcustomLAF(u2,
      |                         ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:62:15: note: ‘HDSidx1’ was declared here
   62 |     HDsidxPtr HDSidx1;
      |               ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:206:25: warning: ‘HDSi1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  206 |     exp_ransacHcustomLAF(u2,
      |                         ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:61:13: note: ‘HDSi1’ was declared here
   61 |     HDsiPtr HDSi1;
      |             ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:206:25: warning: ‘HDS1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  206 |     exp_ransacHcustomLAF(u2,
      |                         ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:60:12: note: ‘HDS1’ was declared here
   60 |     HDsPtr HDS1;
      |            ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp: In function ‘findFundamentalMatrix_’:
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:419:25: warning: ‘SymCheck_th’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  419 |     exp_ransacFcustomLAF(u2,
      |                         ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:297:29: note: ‘SymCheck_th’ was declared here
  297 |     double error_threshold, SymCheck_th;
      |                             ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:419:25: warning: ‘error_threshold’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  419 |     exp_ransacFcustomLAF(u2,
      |                         ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:297:12: note: ‘error_threshold’ was declared here
  297 |     double error_threshold, SymCheck_th;
      |            ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:419:25: warning: ‘FDSidx1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  419 |     exp_ransacFcustomLAF(u2,
      |                         ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:295:15: note: ‘FDSidx1’ was declared here
  295 |     FDsidxPtr FDSidx1;
      |               ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:419:25: warning: ‘EXFDS1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  419 |     exp_ransacFcustomLAF(u2,
      |                         ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:294:14: note: ‘EXFDS1’ was declared here
  294 |     exFDsPtr EXFDS1;
      |              ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:419:25: warning: ‘FDS1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  419 |     exp_ransacFcustomLAF(u2,
      |                         ^
/first_disk/TopKWindows/pydegensac/src/pydegensac/bindings.cpp:293:12: note: ‘FDS1’ was declared here
  293 |     FDsPtr FDS1;
      |            ^
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/pydegensac.dir/build.make:103: ../lib.linux-x86_64-3.10/pydegensac/pydegensac.cpython-310-x86_64-linux-gnu.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/pydegensac.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
Traceback (most recent call last):
  File "/first_disk/TopKWindows/pydegensac/./setup.py", line 100, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/first_disk/TopKWindows/pydegensac/./setup.py", line 38, in run
    self.build_extension(ext)
  File "/first_disk/TopKWindows/pydegensac/./setup.py", line 68, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args,
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.

**Comment by ducha-aiki** [comment]
You can install it from pip for python 3.10
