### ISSUE TITLE
Multiple instances key point detection

### ISSUE THREAD

**Issue by Ademord** [ducha-aiki/pydegensac#6]
Hello
I was wondering if I can use this algorithm to detect from one reference image, multiple instances of the object in a second image 

If not, what would you recommend ?

Thanks in advance

**Comment by ducha-aiki** [comment]
You can do something, called "Sequential RANSAC" -- Run pydegensac, then remove correspondences which are inliers and repeat.
Or run this https://github.com/danini/progressive-x/blob/master/examples/example_multi_homography.ipynb
