### ISSUE TITLE
Windows wheels for pypi/document way to build on windows

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [ducha-aiki/pydegensac#9]
Hi,

currently the build on windows in completely undocumented.
When trying to install via pip, one gets the following output on windows:
```
ERROR: Could not find a version that satisfies the requirement pydegensac
ERROR: No matching distribution found for pydegensac
```

When trying to build on windows, one learns, that one needs to install cmake.

But even after installing cmake one learns in addition, that fortran compiler is needed:
```
running build_ext
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.22.27905.0
-- The CXX compiler identification is MSVC 19.22.27905.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:6 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.
```

, and it is completely unclear, which one should be setup/used

Having windows wheels/or proper documentation for installation on windows would be of help

**Comment by ducha-aiki** [comment]
Hi,

Unfortunately, I have developed for Windows >7 years ago, so have no idea how to do it. If you succeed in creating such instruction/installation, feel free to make al PR.

**Comment by serhiy-yevtushenko** [comment]
Could you clarify, why does this code need Fortran compiler at all? I wonder, as I was not able to find any fortran code in repository.

**Comment by ducha-aiki** [comment]
I believe to link against fortran-based lapack functions.

**Comment by ducha-aiki** [comment]
You can comment-out fortran part and check if it works.

**Comment by serhiy-yevtushenko** [comment]
Unfortunately, no, but reason seems to lay in c macros;

Basically, I got the following error:
\src\pydegensac\degensac\exp_ranF.c(1409,31): error C2059:  syntax error:
'{'  [...\build\temp.win-amd64-3.8\Release\pydegensac_support.vcxproj]

(Pathes edited to remove my specific location)
And then a bunch of other similar errors,
(
 warning C4013:  '__typeof__'
 undefined; assuming extern returning int
: error C2146:  syntax error:
missing ';' before identifier '_b'
)
which are related to this macro

#define min(a,b) \
    ({ __typeof__ (a) _a = (a); \
    __typeof__ (b) _b = (b); \
    _a < _b ? _a : _b; })

I believe one needs to specify, exactly which C++ compiler one expects to be used (I'm using the one from VSCode, and it was enough for other python packages)

**Comment by ducha-aiki** [comment]
No idea, maybe mingw. For Linux it works with gcc

**Comment by serhiy-yevtushenko** [comment]
Hi, nevertheless thanks for the quick responsces.

If one compares pydengensac findHomeography with cv2.findHomeography, what are the main differences? Can one use cv2 one instead pydengensac? If yes, what are the drawbacks?

**Comment by ducha-aiki** [comment]
Yes, you can. It is just that pydegensac outputs correct homography more often for the hard cases.

**Comment by ducha-aiki** [comment]
Wheels are on Pypi, I am closing the issue :)

**Comment by serhiy-yevtushenko** [comment]
Thanks

**Comment by ducha-aiki** [comment]
I will later push the version I was able to build (with mingw-64) to the Windows branch.

**Comment by ducha-aiki** [comment]
The version I managed to build on Windows is in this branch:

https://github.com/ducha-aiki/pydegensac/tree/windows-build-mingw
